// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller_messages.proto

package edu.usfca.cs.dfs;

public final class ControllerMessages {
  private ControllerMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StoreChunkRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StoreChunkRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 fileSize = 1;</code>
     */
    long getFileSize();
  }
  /**
   * Protobuf type {@code StoreChunkRequest}
   */
  public  static final class StoreChunkRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StoreChunkRequest)
      StoreChunkRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreChunkRequest.newBuilder() to construct.
    private StoreChunkRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreChunkRequest() {
      fileSize_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StoreChunkRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              fileSize_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.ControllerMessages.internal_static_StoreChunkRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.ControllerMessages.internal_static_StoreChunkRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.class, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder.class);
    }

    public static final int FILESIZE_FIELD_NUMBER = 1;
    private long fileSize_;
    /**
     * <code>int64 fileSize = 1;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fileSize_ != 0L) {
        output.writeInt64(1, fileSize_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fileSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, fileSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest other = (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) obj;

      boolean result = true;
      result = result && (getFileSize()
          == other.getFileSize());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSize());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StoreChunkRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StoreChunkRequest)
        edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_StoreChunkRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_StoreChunkRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.class, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fileSize_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_StoreChunkRequest_descriptor;
      }

      public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest build() {
        edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest buildPartial() {
        edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest result = new edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest(this);
        result.fileSize_ = fileSize_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) {
          return mergeFrom((edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest other) {
        if (other == edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance()) return this;
        if (other.getFileSize() != 0L) {
          setFileSize(other.getFileSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>int64 fileSize = 1;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>int64 fileSize = 1;</code>
       */
      public Builder setFileSize(long value) {
        
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fileSize = 1;</code>
       */
      public Builder clearFileSize() {
        
        fileSize_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StoreChunkRequest)
    }

    // @@protoc_insertion_point(class_scope:StoreChunkRequest)
    private static final edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest();
    }

    public static edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreChunkRequest>
        PARSER = new com.google.protobuf.AbstractParser<StoreChunkRequest>() {
      public StoreChunkRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StoreChunkRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StoreChunkRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreChunkRequest> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatSignalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatSignal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string metaData = 1;</code>
     */
    java.lang.String getMetaData();
    /**
     * <code>string metaData = 1;</code>
     */
    com.google.protobuf.ByteString
        getMetaDataBytes();

    /**
     * <code>double freeSpace = 2;</code>
     */
    double getFreeSpace();

    /**
     * <code>string timestamp = 3;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();
  }
  /**
   * Protobuf type {@code HeartBeatSignal}
   */
  public  static final class HeartBeatSignal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeartBeatSignal)
      HeartBeatSignalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatSignal.newBuilder() to construct.
    private HeartBeatSignal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatSignal() {
      metaData_ = "";
      freeSpace_ = 0D;
      timestamp_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatSignal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              metaData_ = s;
              break;
            }
            case 17: {

              freeSpace_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.ControllerMessages.internal_static_HeartBeatSignal_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.ControllerMessages.internal_static_HeartBeatSignal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.class, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder.class);
    }

    public static final int METADATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object metaData_;
    /**
     * <code>string metaData = 1;</code>
     */
    public java.lang.String getMetaData() {
      java.lang.Object ref = metaData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metaData_ = s;
        return s;
      }
    }
    /**
     * <code>string metaData = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMetaDataBytes() {
      java.lang.Object ref = metaData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metaData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FREESPACE_FIELD_NUMBER = 2;
    private double freeSpace_;
    /**
     * <code>double freeSpace = 2;</code>
     */
    public double getFreeSpace() {
      return freeSpace_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>string timestamp = 3;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMetaDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, metaData_);
      }
      if (freeSpace_ != 0D) {
        output.writeDouble(2, freeSpace_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMetaDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, metaData_);
      }
      if (freeSpace_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, freeSpace_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal other = (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) obj;

      boolean result = true;
      result = result && getMetaData()
          .equals(other.getMetaData());
      result = result && (
          java.lang.Double.doubleToLongBits(getFreeSpace())
          == java.lang.Double.doubleToLongBits(
              other.getFreeSpace()));
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetaData().hashCode();
      hash = (37 * hash) + FREESPACE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFreeSpace()));
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatSignal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatSignal)
        edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_HeartBeatSignal_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_HeartBeatSignal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.class, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        metaData_ = "";

        freeSpace_ = 0D;

        timestamp_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_HeartBeatSignal_descriptor;
      }

      public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal build() {
        edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal buildPartial() {
        edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal result = new edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal(this);
        result.metaData_ = metaData_;
        result.freeSpace_ = freeSpace_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) {
          return mergeFrom((edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal other) {
        if (other == edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance()) return this;
        if (!other.getMetaData().isEmpty()) {
          metaData_ = other.metaData_;
          onChanged();
        }
        if (other.getFreeSpace() != 0D) {
          setFreeSpace(other.getFreeSpace());
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object metaData_ = "";
      /**
       * <code>string metaData = 1;</code>
       */
      public java.lang.String getMetaData() {
        java.lang.Object ref = metaData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          metaData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string metaData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMetaDataBytes() {
        java.lang.Object ref = metaData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metaData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string metaData = 1;</code>
       */
      public Builder setMetaData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        metaData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string metaData = 1;</code>
       */
      public Builder clearMetaData() {
        
        metaData_ = getDefaultInstance().getMetaData();
        onChanged();
        return this;
      }
      /**
       * <code>string metaData = 1;</code>
       */
      public Builder setMetaDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        metaData_ = value;
        onChanged();
        return this;
      }

      private double freeSpace_ ;
      /**
       * <code>double freeSpace = 2;</code>
       */
      public double getFreeSpace() {
        return freeSpace_;
      }
      /**
       * <code>double freeSpace = 2;</code>
       */
      public Builder setFreeSpace(double value) {
        
        freeSpace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double freeSpace = 2;</code>
       */
      public Builder clearFreeSpace() {
        
        freeSpace_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 3;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 3;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HeartBeatSignal)
    }

    // @@protoc_insertion_point(class_scope:HeartBeatSignal)
    private static final edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal();
    }

    public static edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatSignal>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatSignal>() {
      public HeartBeatSignal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeartBeatSignal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatSignal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatSignal> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControllerMessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ControllerMessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
     */
    boolean hasStoreChunkRequestMsg();
    /**
     * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
     */
    edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest getStoreChunkRequestMsg();
    /**
     * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
     */
    edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder getStoreChunkRequestMsgOrBuilder();

    /**
     * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
     */
    boolean hasHeartBeatSignalMsg();
    /**
     * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
     */
    edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal getHeartBeatSignalMsg();
    /**
     * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
     */
    edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder getHeartBeatSignalMsgOrBuilder();

    public edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code ControllerMessageWrapper}
   */
  public  static final class ControllerMessageWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ControllerMessageWrapper)
      ControllerMessageWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControllerMessageWrapper.newBuilder() to construct.
    private ControllerMessageWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControllerMessageWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControllerMessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.ControllerMessages.internal_static_ControllerMessageWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.ControllerMessages.internal_static_ControllerMessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.class, edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      STORECHUNKREQUESTMSG(1),
      HEARTBEATSIGNALMSG(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return STORECHUNKREQUESTMSG;
          case 2: return HEARTBEATSIGNALMSG;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int STORECHUNKREQUESTMSG_FIELD_NUMBER = 1;
    /**
     * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
     */
    public boolean hasStoreChunkRequestMsg() {
      return msgCase_ == 1;
    }
    /**
     * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest getStoreChunkRequestMsg() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_;
      }
      return edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
    }
    /**
     * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder getStoreChunkRequestMsgOrBuilder() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_;
      }
      return edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
    }

    public static final int HEARTBEATSIGNALMSG_FIELD_NUMBER = 2;
    /**
     * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
     */
    public boolean hasHeartBeatSignalMsg() {
      return msgCase_ == 2;
    }
    /**
     * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal getHeartBeatSignalMsg() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_;
      }
      return edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
    }
    /**
     * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder getHeartBeatSignalMsgOrBuilder() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_;
      }
      return edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper other = (edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getStoreChunkRequestMsg()
              .equals(other.getStoreChunkRequestMsg());
          break;
        case 2:
          result = result && getHeartBeatSignalMsg()
              .equals(other.getHeartBeatSignalMsg());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + STORECHUNKREQUESTMSG_FIELD_NUMBER;
          hash = (53 * hash) + getStoreChunkRequestMsg().hashCode();
          break;
        case 2:
          hash = (37 * hash) + HEARTBEATSIGNALMSG_FIELD_NUMBER;
          hash = (53 * hash) + getHeartBeatSignalMsg().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ControllerMessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ControllerMessageWrapper)
        edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_ControllerMessageWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_ControllerMessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.class, edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.ControllerMessages.internal_static_ControllerMessageWrapper_descriptor;
      }

      public edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper build() {
        edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper buildPartial() {
        edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper result = new edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper(this);
        if (msgCase_ == 1) {
          if (storeChunkRequestMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = storeChunkRequestMsgBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (heartBeatSignalMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = heartBeatSignalMsgBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper) {
          return mergeFrom((edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper other) {
        if (other == edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case STORECHUNKREQUESTMSG: {
            mergeStoreChunkRequestMsg(other.getStoreChunkRequestMsg());
            break;
          }
          case HEARTBEATSIGNALMSG: {
            mergeHeartBeatSignalMsg(other.getHeartBeatSignalMsg());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder> storeChunkRequestMsgBuilder_;
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public boolean hasStoreChunkRequestMsg() {
        return msgCase_ == 1;
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest getStoreChunkRequestMsg() {
        if (storeChunkRequestMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_;
          }
          return edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return storeChunkRequestMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public Builder setStoreChunkRequestMsg(edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest value) {
        if (storeChunkRequestMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          storeChunkRequestMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public Builder setStoreChunkRequestMsg(
          edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder builderForValue) {
        if (storeChunkRequestMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          storeChunkRequestMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public Builder mergeStoreChunkRequestMsg(edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest value) {
        if (storeChunkRequestMsgBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.newBuilder((edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            storeChunkRequestMsgBuilder_.mergeFrom(value);
          }
          storeChunkRequestMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public Builder clearStoreChunkRequestMsg() {
        if (storeChunkRequestMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          storeChunkRequestMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder getStoreChunkRequestMsgBuilder() {
        return getStoreChunkRequestMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder getStoreChunkRequestMsgOrBuilder() {
        if ((msgCase_ == 1) && (storeChunkRequestMsgBuilder_ != null)) {
          return storeChunkRequestMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_;
          }
          return edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.StoreChunkRequest storeChunkRequestMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder> 
          getStoreChunkRequestMsgFieldBuilder() {
        if (storeChunkRequestMsgBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.getDefaultInstance();
          }
          storeChunkRequestMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest.Builder, edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequestOrBuilder>(
                  (edu.usfca.cs.dfs.ControllerMessages.StoreChunkRequest) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return storeChunkRequestMsgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder> heartBeatSignalMsgBuilder_;
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public boolean hasHeartBeatSignalMsg() {
        return msgCase_ == 2;
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal getHeartBeatSignalMsg() {
        if (heartBeatSignalMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_;
          }
          return edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return heartBeatSignalMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
        }
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public Builder setHeartBeatSignalMsg(edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal value) {
        if (heartBeatSignalMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          heartBeatSignalMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public Builder setHeartBeatSignalMsg(
          edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder builderForValue) {
        if (heartBeatSignalMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatSignalMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public Builder mergeHeartBeatSignalMsg(edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal value) {
        if (heartBeatSignalMsgBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.newBuilder((edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            heartBeatSignalMsgBuilder_.mergeFrom(value);
          }
          heartBeatSignalMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public Builder clearHeartBeatSignalMsg() {
        if (heartBeatSignalMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          heartBeatSignalMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder getHeartBeatSignalMsgBuilder() {
        return getHeartBeatSignalMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder getHeartBeatSignalMsgOrBuilder() {
        if ((msgCase_ == 2) && (heartBeatSignalMsgBuilder_ != null)) {
          return heartBeatSignalMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_;
          }
          return edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
        }
      }
      /**
       * <code>.HeartBeatSignal heartBeatSignalMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder> 
          getHeartBeatSignalMsgFieldBuilder() {
        if (heartBeatSignalMsgBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.getDefaultInstance();
          }
          heartBeatSignalMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal.Builder, edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignalOrBuilder>(
                  (edu.usfca.cs.dfs.ControllerMessages.HeartBeatSignal) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return heartBeatSignalMsgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ControllerMessageWrapper)
    }

    // @@protoc_insertion_point(class_scope:ControllerMessageWrapper)
    private static final edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper();
    }

    public static edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControllerMessageWrapper>
        PARSER = new com.google.protobuf.AbstractParser<ControllerMessageWrapper>() {
      public ControllerMessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ControllerMessageWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControllerMessageWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControllerMessageWrapper> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.ControllerMessages.ControllerMessageWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StoreChunkRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StoreChunkRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatSignal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeatSignal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControllerMessageWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControllerMessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031controller_messages.proto\"%\n\021StoreChun" +
      "kRequest\022\020\n\010fileSize\030\001 \001(\003\"I\n\017HeartBeatS" +
      "ignal\022\020\n\010metaData\030\001 \001(\t\022\021\n\tfreeSpace\030\002 \001" +
      "(\001\022\021\n\ttimestamp\030\003 \001(\t\"\205\001\n\030ControllerMess" +
      "ageWrapper\0222\n\024storeChunkRequestMsg\030\001 \001(\013" +
      "2\022.StoreChunkRequestH\000\022.\n\022heartBeatSigna" +
      "lMsg\030\002 \001(\0132\020.HeartBeatSignalH\000B\005\n\003msgB\022\n" +
      "\020edu.usfca.cs.dfsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StoreChunkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StoreChunkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StoreChunkRequest_descriptor,
        new java.lang.String[] { "FileSize", });
    internal_static_HeartBeatSignal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatSignal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeatSignal_descriptor,
        new java.lang.String[] { "MetaData", "FreeSpace", "Timestamp", });
    internal_static_ControllerMessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ControllerMessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControllerMessageWrapper_descriptor,
        new java.lang.String[] { "StoreChunkRequestMsg", "HeartBeatSignalMsg", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
