// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_messages.proto

package edu.usfca.cs.dfs;

public final class StorageMessages {
  private StorageMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StoreChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StoreChunk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fileName = 1;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int32 chunkId = 2;</code>
     */
    int getChunkId();

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>repeated string hostName = 4;</code>
     */
    java.util.List<java.lang.String>
        getHostNameList();
    /**
     * <code>repeated string hostName = 4;</code>
     */
    int getHostNameCount();
    /**
     * <code>repeated string hostName = 4;</code>
     */
    java.lang.String getHostName(int index);
    /**
     * <code>repeated string hostName = 4;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes(int index);
  }
  /**
   * Protobuf type {@code StoreChunk}
   */
  public  static final class StoreChunk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StoreChunk)
      StoreChunkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StoreChunk.newBuilder() to construct.
    private StoreChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StoreChunk() {
      fileName_ = "";
      chunkId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      hostName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StoreChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 16: {

              chunkId_ = input.readInt32();
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hostName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hostName_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hostName_ = hostName_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_StoreChunk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_StoreChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.StoreChunk.class, edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder.class);
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 1;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKID_FIELD_NUMBER = 2;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 2;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int HOSTNAME_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hostName_;
    /**
     * <code>repeated string hostName = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHostNameList() {
      return hostName_;
    }
    /**
     * <code>repeated string hostName = 4;</code>
     */
    public int getHostNameCount() {
      return hostName_.size();
    }
    /**
     * <code>repeated string hostName = 4;</code>
     */
    public java.lang.String getHostName(int index) {
      return hostName_.get(index);
    }
    /**
     * <code>repeated string hostName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes(int index) {
      return hostName_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(2, chunkId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      for (int i = 0; i < hostName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hostName_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chunkId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hostName_.size(); i++) {
          dataSize += computeStringSizeNoTag(hostName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHostNameList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.StoreChunk)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.StoreChunk other = (edu.usfca.cs.dfs.StorageMessages.StoreChunk) obj;

      boolean result = true;
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && getData()
          .equals(other.getData());
      result = result && getHostNameList()
          .equals(other.getHostNameList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      if (getHostNameCount() > 0) {
        hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getHostNameList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.StoreChunk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StoreChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StoreChunk)
        edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_StoreChunk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_StoreChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.StoreChunk.class, edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.StoreChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fileName_ = "";

        chunkId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        hostName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_StoreChunk_descriptor;
      }

      public edu.usfca.cs.dfs.StorageMessages.StoreChunk getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.StorageMessages.StoreChunk build() {
        edu.usfca.cs.dfs.StorageMessages.StoreChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.StorageMessages.StoreChunk buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.StoreChunk result = new edu.usfca.cs.dfs.StorageMessages.StoreChunk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.fileName_ = fileName_;
        result.chunkId_ = chunkId_;
        result.data_ = data_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hostName_ = hostName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hostName_ = hostName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.StoreChunk) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.StoreChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.StoreChunk other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.hostName_.isEmpty()) {
          if (hostName_.isEmpty()) {
            hostName_ = other.hostName_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHostNameIsMutable();
            hostName_.addAll(other.hostName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.StoreChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.StoreChunk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 1;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hostName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHostNameIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hostName_ = new com.google.protobuf.LazyStringArrayList(hostName_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHostNameList() {
        return hostName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public int getHostNameCount() {
        return hostName_.size();
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public java.lang.String getHostName(int index) {
        return hostName_.get(index);
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes(int index) {
        return hostName_.getByteString(index);
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public Builder setHostName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostNameIsMutable();
        hostName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public Builder addHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostNameIsMutable();
        hostName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public Builder addAllHostName(
          java.lang.Iterable<java.lang.String> values) {
        ensureHostNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hostName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public Builder clearHostName() {
        hostName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hostName = 4;</code>
       */
      public Builder addHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureHostNameIsMutable();
        hostName_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StoreChunk)
    }

    // @@protoc_insertion_point(class_scope:StoreChunk)
    private static final edu.usfca.cs.dfs.StorageMessages.StoreChunk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.StoreChunk();
    }

    public static edu.usfca.cs.dfs.StorageMessages.StoreChunk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StoreChunk>
        PARSER = new com.google.protobuf.AbstractParser<StoreChunk>() {
      public StoreChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StoreChunk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StoreChunk> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StoreChunk> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.StorageMessages.StoreChunk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RetrieveFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RetrieveFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fileName = 1;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>string fileName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>int32 chunkId = 2;</code>
     */
    int getChunkId();
  }
  /**
   * Protobuf type {@code RetrieveFile}
   */
  public  static final class RetrieveFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RetrieveFile)
      RetrieveFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RetrieveFile.newBuilder() to construct.
    private RetrieveFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RetrieveFile() {
      fileName_ = "";
      chunkId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RetrieveFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 16: {

              chunkId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_RetrieveFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_RetrieveFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.RetrieveFile.class, edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string fileName = 1;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKID_FIELD_NUMBER = 2;
    private int chunkId_;
    /**
     * <code>int32 chunkId = 2;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (chunkId_ != 0) {
        output.writeInt32(2, chunkId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chunkId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.RetrieveFile)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.RetrieveFile other = (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) obj;

      boolean result = true;
      result = result && getFileName()
          .equals(other.getFileName());
      result = result && (getChunkId()
          == other.getChunkId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.RetrieveFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RetrieveFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RetrieveFile)
        edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_RetrieveFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_RetrieveFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.RetrieveFile.class, edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.RetrieveFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fileName_ = "";

        chunkId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_RetrieveFile_descriptor;
      }

      public edu.usfca.cs.dfs.StorageMessages.RetrieveFile getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.StorageMessages.RetrieveFile build() {
        edu.usfca.cs.dfs.StorageMessages.RetrieveFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.StorageMessages.RetrieveFile buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.RetrieveFile result = new edu.usfca.cs.dfs.StorageMessages.RetrieveFile(this);
        result.fileName_ = fileName_;
        result.chunkId_ = chunkId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.RetrieveFile) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.RetrieveFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.RetrieveFile other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.RetrieveFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string fileName = 1;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string fileName = 1;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkId = 2;</code>
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RetrieveFile)
    }

    // @@protoc_insertion_point(class_scope:RetrieveFile)
    private static final edu.usfca.cs.dfs.StorageMessages.RetrieveFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.RetrieveFile();
    }

    public static edu.usfca.cs.dfs.StorageMessages.RetrieveFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RetrieveFile>
        PARSER = new com.google.protobuf.AbstractParser<RetrieveFile>() {
      public RetrieveFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RetrieveFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RetrieveFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RetrieveFile> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.StorageMessages.RetrieveFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StorageMessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StorageMessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    boolean hasStoreChunkMsg();
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.StoreChunk getStoreChunkMsg();
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder getStoreChunkMsgOrBuilder();

    /**
     * <code>.RetrieveFile retrieveFileMsg = 2;</code>
     */
    boolean hasRetrieveFileMsg();
    /**
     * <code>.RetrieveFile retrieveFileMsg = 2;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.RetrieveFile getRetrieveFileMsg();
    /**
     * <code>.RetrieveFile retrieveFileMsg = 2;</code>
     */
    edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder getRetrieveFileMsgOrBuilder();

    public edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code StorageMessageWrapper}
   */
  public  static final class StorageMessageWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StorageMessageWrapper)
      StorageMessageWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StorageMessageWrapper.newBuilder() to construct.
    private StorageMessageWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StorageMessageWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StorageMessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.StorageMessages.StoreChunk.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(edu.usfca.cs.dfs.StorageMessages.RetrieveFile.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_StorageMessageWrapper_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.cs.dfs.StorageMessages.internal_static_StorageMessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.class, edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite {
      STORECHUNKMSG(1),
      RETRIEVEFILEMSG(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return STORECHUNKMSG;
          case 2: return RETRIEVEFILEMSG;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int STORECHUNKMSG_FIELD_NUMBER = 1;
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    public boolean hasStoreChunkMsg() {
      return msgCase_ == 1;
    }
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.StoreChunk getStoreChunkMsg() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_;
      }
      return edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
    }
    /**
     * <code>.StoreChunk storeChunkMsg = 1;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder getStoreChunkMsgOrBuilder() {
      if (msgCase_ == 1) {
         return (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_;
      }
      return edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
    }

    public static final int RETRIEVEFILEMSG_FIELD_NUMBER = 2;
    /**
     * <code>.RetrieveFile retrieveFileMsg = 2;</code>
     */
    public boolean hasRetrieveFileMsg() {
      return msgCase_ == 2;
    }
    /**
     * <code>.RetrieveFile retrieveFileMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.RetrieveFile getRetrieveFileMsg() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_;
      }
      return edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
    }
    /**
     * <code>.RetrieveFile retrieveFileMsg = 2;</code>
     */
    public edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder getRetrieveFileMsgOrBuilder() {
      if (msgCase_ == 2) {
         return (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_;
      }
      return edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper)) {
        return super.equals(obj);
      }
      edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper other = (edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper) obj;

      boolean result = true;
      result = result && getMsgCase().equals(
          other.getMsgCase());
      if (!result) return false;
      switch (msgCase_) {
        case 1:
          result = result && getStoreChunkMsg()
              .equals(other.getStoreChunkMsg());
          break;
        case 2:
          result = result && getRetrieveFileMsg()
              .equals(other.getRetrieveFileMsg());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + STORECHUNKMSG_FIELD_NUMBER;
          hash = (53 * hash) + getStoreChunkMsg().hashCode();
          break;
        case 2:
          hash = (37 * hash) + RETRIEVEFILEMSG_FIELD_NUMBER;
          hash = (53 * hash) + getRetrieveFileMsg().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StorageMessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StorageMessageWrapper)
        edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_StorageMessageWrapper_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_StorageMessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.class, edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.Builder.class);
      }

      // Construct using edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.cs.dfs.StorageMessages.internal_static_StorageMessageWrapper_descriptor;
      }

      public edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper getDefaultInstanceForType() {
        return edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.getDefaultInstance();
      }

      public edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper build() {
        edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper buildPartial() {
        edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper result = new edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper(this);
        if (msgCase_ == 1) {
          if (storeChunkMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = storeChunkMsgBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (retrieveFileMsgBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = retrieveFileMsgBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper) {
          return mergeFrom((edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper other) {
        if (other == edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case STORECHUNKMSG: {
            mergeStoreChunkMsg(other.getStoreChunkMsg());
            break;
          }
          case RETRIEVEFILEMSG: {
            mergeRetrieveFileMsg(other.getRetrieveFileMsg());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.StorageMessages.StoreChunk, edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder, edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder> storeChunkMsgBuilder_;
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public boolean hasStoreChunkMsg() {
        return msgCase_ == 1;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.StoreChunk getStoreChunkMsg() {
        if (storeChunkMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_;
          }
          return edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return storeChunkMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
        }
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder setStoreChunkMsg(edu.usfca.cs.dfs.StorageMessages.StoreChunk value) {
        if (storeChunkMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          storeChunkMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder setStoreChunkMsg(
          edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder builderForValue) {
        if (storeChunkMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          storeChunkMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder mergeStoreChunkMsg(edu.usfca.cs.dfs.StorageMessages.StoreChunk value) {
        if (storeChunkMsgBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.StorageMessages.StoreChunk.newBuilder((edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            storeChunkMsgBuilder_.mergeFrom(value);
          }
          storeChunkMsgBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public Builder clearStoreChunkMsg() {
        if (storeChunkMsgBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          storeChunkMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder getStoreChunkMsgBuilder() {
        return getStoreChunkMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder getStoreChunkMsgOrBuilder() {
        if ((msgCase_ == 1) && (storeChunkMsgBuilder_ != null)) {
          return storeChunkMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_;
          }
          return edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
        }
      }
      /**
       * <code>.StoreChunk storeChunkMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.StorageMessages.StoreChunk, edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder, edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder> 
          getStoreChunkMsgFieldBuilder() {
        if (storeChunkMsgBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = edu.usfca.cs.dfs.StorageMessages.StoreChunk.getDefaultInstance();
          }
          storeChunkMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.StorageMessages.StoreChunk, edu.usfca.cs.dfs.StorageMessages.StoreChunk.Builder, edu.usfca.cs.dfs.StorageMessages.StoreChunkOrBuilder>(
                  (edu.usfca.cs.dfs.StorageMessages.StoreChunk) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return storeChunkMsgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.StorageMessages.RetrieveFile, edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder, edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder> retrieveFileMsgBuilder_;
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public boolean hasRetrieveFileMsg() {
        return msgCase_ == 2;
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.RetrieveFile getRetrieveFileMsg() {
        if (retrieveFileMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_;
          }
          return edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return retrieveFileMsgBuilder_.getMessage();
          }
          return edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
        }
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public Builder setRetrieveFileMsg(edu.usfca.cs.dfs.StorageMessages.RetrieveFile value) {
        if (retrieveFileMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          retrieveFileMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public Builder setRetrieveFileMsg(
          edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder builderForValue) {
        if (retrieveFileMsgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          retrieveFileMsgBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public Builder mergeRetrieveFileMsg(edu.usfca.cs.dfs.StorageMessages.RetrieveFile value) {
        if (retrieveFileMsgBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance()) {
            msg_ = edu.usfca.cs.dfs.StorageMessages.RetrieveFile.newBuilder((edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            retrieveFileMsgBuilder_.mergeFrom(value);
          }
          retrieveFileMsgBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public Builder clearRetrieveFileMsg() {
        if (retrieveFileMsgBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          retrieveFileMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder getRetrieveFileMsgBuilder() {
        return getRetrieveFileMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      public edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder getRetrieveFileMsgOrBuilder() {
        if ((msgCase_ == 2) && (retrieveFileMsgBuilder_ != null)) {
          return retrieveFileMsgBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_;
          }
          return edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
        }
      }
      /**
       * <code>.RetrieveFile retrieveFileMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          edu.usfca.cs.dfs.StorageMessages.RetrieveFile, edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder, edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder> 
          getRetrieveFileMsgFieldBuilder() {
        if (retrieveFileMsgBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = edu.usfca.cs.dfs.StorageMessages.RetrieveFile.getDefaultInstance();
          }
          retrieveFileMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              edu.usfca.cs.dfs.StorageMessages.RetrieveFile, edu.usfca.cs.dfs.StorageMessages.RetrieveFile.Builder, edu.usfca.cs.dfs.StorageMessages.RetrieveFileOrBuilder>(
                  (edu.usfca.cs.dfs.StorageMessages.RetrieveFile) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return retrieveFileMsgBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StorageMessageWrapper)
    }

    // @@protoc_insertion_point(class_scope:StorageMessageWrapper)
    private static final edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper();
    }

    public static edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StorageMessageWrapper>
        PARSER = new com.google.protobuf.AbstractParser<StorageMessageWrapper>() {
      public StorageMessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StorageMessageWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StorageMessageWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StorageMessageWrapper> getParserForType() {
      return PARSER;
    }

    public edu.usfca.cs.dfs.StorageMessages.StorageMessageWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StoreChunk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StoreChunk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RetrieveFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RetrieveFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StorageMessageWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StorageMessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026storage_messages.proto\"O\n\nStoreChunk\022\020" +
      "\n\010fileName\030\001 \001(\t\022\017\n\007chunkId\030\002 \001(\005\022\014\n\004dat" +
      "a\030\003 \001(\014\022\020\n\010hostName\030\004 \003(\t\"1\n\014RetrieveFil" +
      "e\022\020\n\010fileName\030\001 \001(\t\022\017\n\007chunkId\030\002 \001(\005\"n\n\025" +
      "StorageMessageWrapper\022$\n\rstoreChunkMsg\030\001" +
      " \001(\0132\013.StoreChunkH\000\022(\n\017retrieveFileMsg\030\002" +
      " \001(\0132\r.RetrieveFileH\000B\005\n\003msgB\022\n\020edu.usfc" +
      "a.cs.dfsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StoreChunk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StoreChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StoreChunk_descriptor,
        new java.lang.String[] { "FileName", "ChunkId", "Data", "HostName", });
    internal_static_RetrieveFile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RetrieveFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RetrieveFile_descriptor,
        new java.lang.String[] { "FileName", "ChunkId", });
    internal_static_StorageMessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StorageMessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StorageMessageWrapper_descriptor,
        new java.lang.String[] { "StoreChunkMsg", "RetrieveFileMsg", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
